/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1ProductsRouteImport } from './routes/api/public/v1/products'
import { Route as ApiPublicV1ProductsIdRouteImport } from './routes/api/public/v1/products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsRoute = ApiPublicV1ProductsRouteImport.update({
  id: '/api/public/v1/products',
  path: '/api/public/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsIdRoute = ApiPublicV1ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$id': typeof ApiPublicV1ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$id': typeof ApiPublicV1ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$id': typeof ApiPublicV1ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/v1/products' | '/api/public/v1/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/v1/products' | '/api/public/v1/products/$id'
  id:
    | '__root__'
    | '/'
    | '/api/public/v1/products'
    | '/api/public/v1/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicV1ProductsRoute: typeof ApiPublicV1ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products': {
      id: '/api/public/v1/products'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products'
      preLoaderRoute: typeof ApiPublicV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products/$id': {
      id: '/api/public/v1/products/$id'
      path: '/$id'
      fullPath: '/api/public/v1/products/$id'
      preLoaderRoute: typeof ApiPublicV1ProductsIdRouteImport
      parentRoute: typeof ApiPublicV1ProductsRoute
    }
  }
}

interface ApiPublicV1ProductsRouteChildren {
  ApiPublicV1ProductsIdRoute: typeof ApiPublicV1ProductsIdRoute
}

const ApiPublicV1ProductsRouteChildren: ApiPublicV1ProductsRouteChildren = {
  ApiPublicV1ProductsIdRoute: ApiPublicV1ProductsIdRoute,
}

const ApiPublicV1ProductsRouteWithChildren =
  ApiPublicV1ProductsRoute._addFileChildren(ApiPublicV1ProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicV1ProductsRoute: ApiPublicV1ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
